### ISSUE TITLE
Better handling queries that returned an error

### ISSUE THREAD

**Issue by wardweistra** [thehyve/glowing-bear#146]
When an error is returned for a patient query it will currently show up as a 0 patient count:
![screenshot](https://user-images.githubusercontent.com/779157/29022390-65d95732-7b69-11e7-854b-8cb3181c9a60.png)

Please show an error icon where the loading icon normally goes if the query returned an error instead. Please make the mouseover text for the error icon something like: "The patient query returned an error from the server" possibly enhanced with the actual error that was returned.

**Comment by beaugogh** [comment]
part of the apples release now
