### ISSUE TITLE
Show human readable concept names instead of full conceptPath

### ISSUE THREAD

**Issue by wardweistra** [thehyve/glowing-bear#148]
Currently a concept constraint in the query interface shows the full conceptPath. This looks scary for a real user. Please place focus on (in this order):
* The last item of the conceptPath. This will be the human readable, cross-study name of the concept. Parsed to i.a. change '_' to ' '.
* The concept code. This should be an unambiguous way of referencing to the concept.
* Possibly: the rest of the conceptPath, but likely not essential.

For example, a concept with:
* conceptPath: \\Ontologies\\SNOMED_CT\\Observable_entity\\Age_AND/OR_growth_period\\Current_chronological_age\\
* conceptCode: “SNOMEDCT:424144002”

could be shown as "Current chronological age (SNOMEDCT:424144002)"

**Comment by beaugogh** [comment]
TODOs:
1) data loading: add concept codes to concept nodes in the data
2) glowing bear UI: for a concept constraint box, display the last part of the concept fullName path + concept code

**Comment by wardweistra** [comment]
Regarding TODO1: I'm pretty sure that's a backend API adjustment, rather than data loading.

**Comment by wardweistra** [comment]
Human readable concept names are now here
